import { BottledWater } from './types';

export const bottledWaterData: BottledWater[] = [
    {
        id: 1,
        name: '제주 삼다수',
        source: '제주시 조천읍 교래리',
        description2: '클린한 커피를 마시고 싶다면',
        pH: '7.8',
        hardness: '20',
        calcium: '2.5~4.0',
        magnesium: '1.7~3.5',
        potassium: '1.5~3.4',
        sodium: '4.0~7.2',
        gradient: 'bg-gradient-to-br from-blue-500 to-cyan-400',
        textColor: 'text-blue-600',
        bgColor: 'bg-blue-600',
        lightBg: 'bg-blue-50',
        darkBg: 'bg-blue-500',
        borderColor: 'border-blue-200',
        priority: 3,
        hardnessClass: '연수',
        pHClass: '약알칼리성',
        waterType: '클린한 맛',
    },
    {
        id: 2,
        name: '평창수',
        source: '강원도 평창군',
        description2: '커피의 단맛과 바디감을 원한다면',
        pH: '7.8',
        hardness: '70',
        calcium: '15.1~16.2',
        magnesium: '2.3~2.5',
        potassium: '0.6~0.7',
        sodium: '6.2~6.6',
        gradient: 'bg-gradient-to-br from-emerald-500 to-green-400',
        textColor: 'text-emerald-600',
        bgColor: 'bg-emerald-600',
        lightBg: 'bg-emerald-50',
        darkBg: 'bg-emerald-500',
        borderColor: 'border-emerald-200',
        priority: 1,
        hardnessClass: '약경수',
        pHClass: '약알칼리성',
        waterType: '바디감 강조',
    },
    {
        id: 3,
        name: '아이시스 8.0',
        source: '충북 청주 상당구 미원면',
        description2: '커피의 화사함과 밝은 산미를 원한다면',
        pH: '8.0',
        hardness: '60',
        calcium: '14.6~22.0',
        magnesium: '6.1~7.1',
        potassium: '0.8~1.1',
        sodium: '1.9~2.4',
        gradient: 'bg-gradient-to-br from-purple-500 to-violet-400',
        textColor: 'text-purple-600',
        bgColor: 'bg-purple-600',
        lightBg: 'bg-purple-50',
        darkBg: 'bg-purple-500',
        borderColor: 'border-purple-200',
        priority: 2,
        hardnessClass: '연수',
        pHClass: '알칼리성',
        waterType: '밝은 산미',
    },
    {
        id: 4,
        name: '백산수',
        source: '백두산 내두천',
        description2: '균형잡힌 맛을 원한다면',
        pH: '7.2~7.4',
        hardness: '30',
        calcium: '1.4~5.3',
        magnesium: '2.1~5.4',
        potassium: '1.4~5.3',
        sodium: '4.0~12.0',
        gradient: 'bg-gradient-to-br from-amber-500 to-yellow-400',
        textColor: 'text-amber-600',
        bgColor: 'bg-amber-600',
        lightBg: 'bg-amber-50',
        darkBg: 'bg-amber-500',
        borderColor: 'border-amber-200',
        priority: 3,
        hardnessClass: '연수',
        pHClass: '중성',
        waterType: '균형잡힌 맛',
    },
];
